// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person1.proto

package main

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person1_PhoneType int32

const (
	Person1_MOBILE Person1_PhoneType = 0
	Person1_HOME   Person1_PhoneType = 1
	Person1_WORK   Person1_PhoneType = 2
)

var Person1_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var Person1_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person1_PhoneType) String() string {
	return proto.EnumName(Person1_PhoneType_name, int32(x))
}

func (Person1_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_42facf08b2ec409f, []int{0, 0}
}

type Person1 struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Email                string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                []*Person1_PhoneNumber `protobuf:"bytes,4,rep,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Person1) Reset()         { *m = Person1{} }
func (m *Person1) String() string { return proto.CompactTextString(m) }
func (*Person1) ProtoMessage()    {}
func (*Person1) Descriptor() ([]byte, []int) {
	return fileDescriptor_42facf08b2ec409f, []int{0}
}

func (m *Person1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person1.Unmarshal(m, b)
}
func (m *Person1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person1.Marshal(b, m, deterministic)
}
func (m *Person1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person1.Merge(m, src)
}
func (m *Person1) XXX_Size() int {
	return xxx_messageInfo_Person1.Size(m)
}
func (m *Person1) XXX_DiscardUnknown() {
	xxx_messageInfo_Person1.DiscardUnknown(m)
}

var xxx_messageInfo_Person1 proto.InternalMessageInfo

func (m *Person1) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person1) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person1) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person1) GetPhone() []*Person1_PhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

type Person1_PhoneNumber struct {
	Number               string            `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 Person1_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=Person1_PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Person1_PhoneNumber) Reset()         { *m = Person1_PhoneNumber{} }
func (m *Person1_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Person1_PhoneNumber) ProtoMessage()    {}
func (*Person1_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_42facf08b2ec409f, []int{0, 0}
}

func (m *Person1_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person1_PhoneNumber.Unmarshal(m, b)
}
func (m *Person1_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person1_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Person1_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person1_PhoneNumber.Merge(m, src)
}
func (m *Person1_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Person1_PhoneNumber.Size(m)
}
func (m *Person1_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Person1_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Person1_PhoneNumber proto.InternalMessageInfo

func (m *Person1_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person1_PhoneNumber) GetType() Person1_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person1_MOBILE
}

func init() {
	proto.RegisterEnum("Person1_PhoneType", Person1_PhoneType_name, Person1_PhoneType_value)
	proto.RegisterType((*Person1)(nil), "Person1")
	proto.RegisterType((*Person1_PhoneNumber)(nil), "Person1.PhoneNumber")
}

func init() { proto.RegisterFile("person1.proto", fileDescriptor_42facf08b2ec409f) }

var fileDescriptor_42facf08b2ec409f = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0x33, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x7a, 0xcd, 0xc8, 0xc5, 0x1e, 0x00,
	0x11, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x02, 0xb3, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x98,
	0x32, 0x53, 0x84, 0x44, 0xb8, 0x58, 0x53, 0x73, 0x13, 0x33, 0x73, 0x24, 0x98, 0xc1, 0x8a, 0x20,
	0x1c, 0x21, 0x2d, 0x2e, 0xd6, 0x82, 0x8c, 0xfc, 0xbc, 0x54, 0x09, 0x16, 0x05, 0x66, 0x0d, 0x6e,
	0x23, 0x11, 0x3d, 0xa8, 0x91, 0x7a, 0x01, 0x20, 0x51, 0xbf, 0xd2, 0xdc, 0xa4, 0xd4, 0xa2, 0x20,
	0x88, 0x12, 0x29, 0x5f, 0x2e, 0x6e, 0x24, 0x51, 0x21, 0x31, 0x2e, 0xb6, 0x3c, 0x30, 0x0b, 0x6a,
	0x2d, 0x94, 0x27, 0xa4, 0xc6, 0xc5, 0x52, 0x52, 0x59, 0x90, 0x0a, 0xb6, 0x9a, 0xcf, 0x48, 0x08,
	0xd5, 0xc4, 0x90, 0xca, 0x82, 0xd4, 0x20, 0xb0, 0xbc, 0x92, 0x36, 0x17, 0x27, 0x5c, 0x48, 0x88,
	0x8b, 0x8b, 0xcd, 0xd7, 0xdf, 0xc9, 0xd3, 0xc7, 0x55, 0x80, 0x41, 0x88, 0x83, 0x8b, 0xc5, 0xc3,
	0xdf, 0xd7, 0x55, 0x80, 0x11, 0xc4, 0x0a, 0xf7, 0x0f, 0xf2, 0x16, 0x60, 0x4a, 0x62, 0x03, 0x7b,
	0xda, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x03, 0xeb, 0xe4, 0xc2, 0x05, 0x01, 0x00, 0x00,
}
